SRC=XP101.md
# pandoc -s --mathml -i -t dzslides $(SRC) -o XP101_slides.html
all:
	pandoc -s -i $(SRC) -o XP101.html
	pandoc -s -i $(SRC) -o XP101.docx
	pandoc -s --mathml -i -t dzslides $(SRC) -o XP101_slides.html
