Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.define "controller" do |ctrl|
    ctrl.vm.box = "ubuntu/xenial64"

    ctrl.vm.synced_folder "../..", "/mnt/PLaaS"

    ctrl.vm.provision :shell, path: "bootstrap.sh"
    ctrl.vm.hostname = "controller"
  end
end
