---
- name: Upgrade servers and install tooling
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Install packages
    apt:
      name: "{{item}}"
      state: present
    with_items:
    - jq
    - tree
    - aptitude
    - apache2-utils
